s1[0]=A
s1[1]=B
s1[2]=C
s1[3]=D
s1[image]="kathara/sdn"

client1[0]=A
client1[image]="kathara/base"

client2[0]=A
client2[image]="kathara/base"

client3[0]=A
client3[image]="kathara/base"

client4[0]=A
client4[image]="kathara/base"

server1[0]=B
server1[image]="kathara/base"

server2[0]=B
server2[image]="kathara/base"

server3[0]=B
server3[image]="kathara/base"

controller[0]=C
controller[bridged]="True"
controller[image]="kathara/pox"
